@extends('documents.base')
@section('document-title', $t('Optical Order Form', 'نموذج طلب نظارة').' '.$record->order_number)
@section('document')
<main class="document-page">
    @include('documents.partials.watermark')
    <div class="document-content">
        @include('documents.partials.header')
        <h1 class="doc-title">{{ $t('Optical Order Form', 'نموذج طلب نظارة') }}</h1>
        <div class="meta-grid"><div class="meta-cell"><span class="meta-label">{{ $t('Order No.', 'رقم الطلب') }}</span><span class="meta-value">{{ $record->order_number }}</span></div><div class="meta-cell"><span class="meta-label">{{ $t('Date', 'التاريخ') }}</span><span class="meta-value">{{ $record->order_date }}</span></div><div class="meta-cell"><span class="meta-label">{{ $t('Expected', 'التسليم المتوقع') }}</span><span class="meta-value">{{ $record->expected_delivery_date }}</span></div><div class="meta-cell"><span class="meta-label">{{ $t('Status', 'الحالة') }}</span><span class="meta-value">{{ str($record->status)->replace('_', ' ')->title() }}</span></div><div class="meta-cell wide"><span class="meta-label">{{ $t('Patient', 'المريض') }}</span><span class="meta-value">{{ $record->patient_name }} / {{ $record->patient_code }}</span></div><div class="meta-cell"><span class="meta-label">{{ $t('Contact', 'التواصل') }}</span><span class="meta-value">{{ $record->phone ?: $record->whatsapp_number }}</span></div><div class="meta-cell"><span class="meta-label">{{ $t('Salesperson', 'موظف المبيعات') }}</span><span class="meta-value">{{ $record->salesperson_name ?: '-' }}</span></div></div>
        @if($record->prescription)<div class="section-title">{{ $t('Prescription', 'الوصفة') }} {{ $record->prescription->prescription_number }}</div><table class="rx-table"><thead><tr><th>{{ $t('Eye', 'العين') }}</th><th>SPH</th><th>CYL</th><th>AXIS</th><th>V.A.</th><th>ADD</th><th>P.D.</th></tr></thead><tbody><tr><th>RIGHT</th><td>{{ $record->prescription->right_sph }}</td><td>{{ $record->prescription->right_cyl }}</td><td>{{ $record->prescription->right_axis }}</td><td>{{ $record->prescription->right_va }}</td><td>{{ $record->prescription->right_add }}</td><td>{{ $record->prescription->right_pd }}</td></tr><tr><th>LEFT</th><td>{{ $record->prescription->left_sph }}</td><td>{{ $record->prescription->left_cyl }}</td><td>{{ $record->prescription->left_axis }}</td><td>{{ $record->prescription->left_va }}</td><td>{{ $record->prescription->left_add }}</td><td>{{ $record->prescription->left_pd }}</td></tr></tbody></table>@endif
        <div class="section-title">{{ $t('Frame and lenses', 'الإطار والعدسات') }}</div><table><thead><tr><th>#</th><th>{{ $t('Type', 'النوع') }}</th><th>{{ $t('SKU', 'الرمز') }}</th><th>{{ $t('Description', 'الوصف') }}</th><th>{{ $t('Brand', 'الماركة') }}</th><th>{{ $t('Qty', 'الكمية') }}</th><th>{{ $t('Price', 'السعر') }}</th><th>{{ $t('Total', 'الإجمالي') }}</th></tr></thead><tbody>@foreach($record->items as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ str($item->item_type)->replace('_', ' ')->title() }}</td><td>{{ $item->sku }}</td><td>{{ $item->description }}</td><td>{{ $item->brand }}</td><td>{{ number_format($item->quantity, 2) }}</td><td class="numeric">{{ number_format($item->unit_price, 2) }}</td><td class="numeric">{{ number_format($item->line_total, 2) }}</td></tr>@endforeach</tbody></table>
        <div class="meta-grid"><div class="meta-cell"><span class="meta-label">{{ $t('Lens type', 'نوع العدسة') }}</span><span class="meta-value">{{ $record->lens_type }}</span></div><div class="meta-cell"><span class="meta-label">{{ $t('Material', 'الخامة') }}</span><span class="meta-value">{{ $record->lens_material }}</span></div><div class="meta-cell"><span class="meta-label">{{ $t('Index', 'المعامل') }}</span><span class="meta-value">{{ $record->lens_index }}</span></div><div class="meta-cell"><span class="meta-label">{{ $t('Coating / Tint', 'الطلاء / اللون') }}</span><span class="meta-value">{{ $record->coating }} / {{ $record->tint }}</span></div><div class="meta-cell wide"><span class="meta-label">{{ $t('Fitting notes', 'ملاحظات التركيب') }}</span><span class="meta-value">{{ $record->fitting_notes }}</span></div><div class="meta-cell wide"><span class="meta-label">{{ $t('Special instructions', 'تعليمات خاصة') }}</span><span class="meta-value">{{ $record->special_instructions }}</span></div></div>
        <div class="totals"><div class="totals-row grand"><span>{{ $t('Total', 'الإجمالي') }}</span><strong>{{ $branding['currency'] }} {{ number_format($record->grand_total, 2) }}</strong></div><div class="totals-row"><span>{{ $t('Paid', 'المدفوع') }}</span><strong>{{ $branding['currency'] }} {{ number_format($record->paid_amount, 2) }}</strong></div><div class="totals-row"><span>{{ $t('Balance', 'المتبقي') }}</span><strong>{{ $branding['currency'] }} {{ number_format($record->outstanding_amount, 2) }}</strong></div></div>
        <div class="signature-grid"><div class="signature">{{ $branding['prepared_by_ar'] }} / {{ $branding['prepared_by_en'] }}<br>{{ $record->salesperson_name }}</div><div class="signature">{{ $t('Lab', 'المعمل') }}<br>{{ $record->lab_name }}</div><div class="signature">{{ $branding['received_by_ar'] }} / {{ $branding['received_by_en'] }}</div></div>
        @include('documents.partials.footer')
    </div>
</main>
@endsection
