@extends('layouts.erp', ['activeNav' => 'appointments'])

@section('title', __('nav.appointments'))

@php
    $selected = $selectedAppointment ?? [];
    $currentAppointment = $selected['appointment'] ?? null;
    $cards = [
        ['icon' => 'appointments', 'key' => 'calendar', 'page' => 'calendar', 'count' => $metrics['today'] ?? 0],
        ['icon' => 'plus', 'key' => 'book', 'page' => 'create', 'count' => null],
        ['icon' => 'patients', 'key' => 'waiting', 'page' => 'waiting-list', 'count' => $metrics['waiting'] ?? 0],
        ['icon' => 'whatsapp', 'key' => 'followups', 'page' => 'follow-ups', 'count' => $metrics['pending_followups'] ?? 0],
        ['icon' => 'reports', 'key' => 'no_shows', 'page' => 'no-shows', 'count' => $metrics['no_show_month'] ?? 0],
        ['icon' => 'reports', 'key' => 'reports', 'page' => 'reports', 'count' => null],
    ];
@endphp

@section('content')
    @if (! $databaseReady)
        <x-empty-state :title="__('setup.database_not_ready')" :message="__('setup.run_migrations')" />
    @else
        <section class="page-header"><div><p class="eyebrow">{{ __('nav.appointments') }}</p><h1>{{ __('appointments.page.'.$page) }}</h1><p>{{ __('appointments.subtitle') }}</p></div><a class="button" href="{{ route('appointments.app', ['page' => 'create', 'lang' => app()->getLocale()]) }}"><x-icon name="plus" />{{ __('appointments.book') }}</a></section>

        @if($page === 'dashboard')
            <section class="metric-grid"><x-metric-card :label="__('appointments.today')" :value="$metrics['today']" /><x-metric-card :label="__('appointments.confirmed')" :value="$metrics['confirmed']" /><x-metric-card :label="__('appointments.waiting_now')" :value="$metrics['waiting']" /><x-metric-card :label="__('appointments.overdue_followups')" :value="$metrics['overdue_followups']" /></section>
            <section class="section"><div class="section-header"><div><h2>{{ __('appointments.workspace') }}</h2><p>{{ __('appointments.workspace_hint') }}</p></div></div><div class="module-grid">@foreach($cards as $card)<x-module-card :icon="$card['icon']" :title="__('appointments.card.'.$card['key'].'.title')" :description="__('appointments.card.'.$card['key'].'.description')" :action="__('common.open')" :href="route('appointments.app', ['page' => $card['page'], 'lang' => app()->getLocale()])" :count="$card['count']" />@endforeach</div></section>
        @endif

        @if($page === 'calendar')
            <form class="filterbar" method="GET"><input type="hidden" name="lang" value="{{ app()->getLocale() }}"><input name="q" value="{{ $query }}" type="search" placeholder="{{ __('appointments.search_placeholder') }}"><input name="date" value="{{ $date }}" type="date"><select name="status"><option value="">{{ __('appointments.all_statuses') }}</option>@foreach($statuses as $key => $label)<option value="{{ $key }}" @selected($statusFilter === $key)>{{ $label }}</option>@endforeach</select><button class="button button-secondary" type="submit">{{ __('common.search') }}</button></form>
            <section class="table-card"><div class="table-scroll"><table><thead><tr><th>{{ __('appointments.time') }}</th><th>{{ __('patients.patient') }}</th><th>{{ __('appointments.visit_type') }}</th><th>{{ __('patients.optometrist') }}</th><th>{{ __('common.status') }}</th><th></th></tr></thead><tbody>@forelse($appointments as $appointment)<tr><td>{{ \Illuminate\Support\Carbon::parse($appointment->appointment_at)->format('Y-m-d H:i') }}</td><td><strong>{{ $appointment->patient_name }}</strong><br><span class="table-meta">{{ $appointment->patient_code }} / {{ $appointment->phone ?? $appointment->whatsapp_number }}</span></td><td>{{ $appointmentTypes[$appointment->appointment_type] ?? $appointment->appointment_type }}</td><td>{{ $appointment->optometrist_name ?: __('common.not_set') }}</td><td><x-status-badge :status="$appointment->status" /></td><td><a class="button button-ghost" href="{{ route('appointments.app', ['page' => 'details', 'appointment_id' => $appointment->id]) }}">{{ __('common.open') }}</a></td></tr>@empty<tr><td colspan="6"><x-empty-state /></td></tr>@endforelse</tbody></table></div></section>
        @endif

        @if($page === 'create')
            <form method="POST" action="{{ route('appointments.store') }}" data-wizard data-draft-key="appointment-booking-draft">@csrf
                <section class="wizard"><aside class="wizard-steps">@foreach(['patient','visit','time','review'] as $index => $step)<button class="wizard-step-button {{ $index === 0 ? 'active' : '' }}" type="button" data-wizard-step="{{ $step }}"><span class="wizard-step-number">{{ $index + 1 }}</span><span>{{ __('appointments.step.'.$step) }}</span></button>@endforeach</aside><div>
                    <div class="wizard-panel active" data-wizard-panel="patient"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('appointments.choose_patient') }}</h2><div class="field"><label class="required">{{ __('patients.patient') }}</label><select name="patient_id" required>@foreach($patients as $patient)<option value="{{ $patient->id }}" @selected(request('patient_id') == $patient->id)>{{ $patient->patient_code }} - {{ $patient->full_name }} - {{ $patient->phone ?? $patient->whatsapp_number }}</option>@endforeach</select></div><div class="wizard-actions"><a class="button button-ghost" href="{{ route('appointments.app', ['page' => 'dashboard']) }}">{{ __('common.cancel') }}</a><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="visit"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('appointments.visit_details') }}</h2><div class="form-grid"><div class="field"><label class="required">{{ __('appointments.visit_type') }}</label><select name="appointment_type" required>@foreach($appointmentTypes as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('patients.optometrist') }}</label><select name="assigned_to"><option value="">{{ __('common.not_set') }}</option>@foreach($optometrists as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div><div class="field"><label>{{ __('common.branch') }}</label><select name="branch_id">@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($branchId === (int)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="field"><label>{{ __('common.status') }}</label><select name="status">@foreach($statuses as $key => $label)<option value="{{ $key }}" @selected($key === 'scheduled')>{{ $label }}</option>@endforeach</select></div></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="time"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('appointments.choose_time') }}</h2><div class="form-grid"><div class="field"><label class="required">{{ __('common.date') }}</label><input name="appointment_date" type="date" required value="{{ $date }}"></div><div class="field"><label class="required">{{ __('appointments.time') }}</label><input name="appointment_time" type="time" required value="10:00"></div><div class="field"><label class="required">{{ __('appointments.duration') }}</label><input name="duration_minutes" type="number" min="5" step="5" required value="30"></div><details class="more-details"><summary>{{ __('common.more_details') }}</summary><div class="form-grid" style="margin-top:12px"><div class="field"><label>{{ __('appointments.visit_reason') }}</label><textarea name="visit_reason"></textarea></div><div class="field"><label>{{ __('common.notes') }}</label><textarea name="notes"></textarea></div></div></details></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="review"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('appointments.review_booking') }}</h2><p>{{ __('appointments.review_hint') }}</p><div class="notice notice-success">{{ __('common.draft_saved') }}</div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="submit">{{ __('appointments.confirm_booking') }}</button></div></div>
                </div></section>
            </form>
        @endif

        @if($page === 'details')
            @if($currentAppointment)
                <section class="panel"><div class="section-header"><div><h2>{{ $currentAppointment->patient_name }}</h2><p>{{ $currentAppointment->appointment_number }} / {{ $currentAppointment->appointment_at }}</p></div><x-status-badge :status="$currentAppointment->status" /></div><div class="metric-grid"><x-metric-card :label="__('appointments.visit_type')" :value="$appointmentTypes[$currentAppointment->appointment_type] ?? $currentAppointment->appointment_type" /><x-metric-card :label="__('common.branch')" :value="$currentAppointment->branch_name ?: __('common.not_set')" /><x-metric-card :label="__('patients.optometrist')" :value="$currentAppointment->optometrist_name ?: __('common.not_set')" /><x-metric-card :label="__('appointments.duration')" :value="$currentAppointment->duration_minutes.' '.__('appointments.minutes')" /></div><form class="form-grid" method="POST" action="{{ route('appointments.status') }}">@csrf<input type="hidden" name="appointment_id" value="{{ $currentAppointment->id }}"><div class="field"><label>{{ __('common.status') }}</label><select name="status">@foreach($statuses as $key => $label)<option value="{{ $key }}" @selected($currentAppointment->status === $key)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('common.notes') }}</label><input name="notes"></div><div class="form-actions"><a class="button button-ghost" href="{{ route('patients.app', ['page' => 'eye-exam', 'patient_id' => $currentAppointment->patient_id]) }}">{{ __('patients.new_exam') }}</a><button class="button" type="submit">{{ __('appointments.update_status') }}</button></div></form></section>
            @else<x-empty-state />@endif
        @endif

        @if($page === 'waiting-list')
            <section class="table-card"><div class="table-scroll"><table><thead><tr><th>{{ __('appointments.time') }}</th><th>{{ __('patients.patient') }}</th><th>{{ __('appointments.visit_type') }}</th><th>{{ __('common.status') }}</th><th>{{ __('common.manage') }}</th></tr></thead><tbody>@forelse($waitingList as $appointment)<tr><td>{{ \Illuminate\Support\Carbon::parse($appointment->appointment_at)->format('H:i') }}</td><td>{{ $appointment->patient_name }}<br><span class="table-meta">{{ $appointment->phone ?? $appointment->whatsapp_number }}</span></td><td>{{ $appointmentTypes[$appointment->appointment_type] ?? $appointment->appointment_type }}</td><td><x-status-badge :status="$appointment->status" /></td><td><form style="display:flex;gap:8px" method="POST" action="{{ route('appointments.status') }}">@csrf<input type="hidden" name="appointment_id" value="{{ $appointment->id }}"><select name="status"><option value="waiting">{{ $statuses['waiting'] ?? __('status.waiting') }}</option><option value="in_examination">{{ $statuses['in_examination'] ?? __('status.in_examination') }}</option><option value="completed">{{ $statuses['completed'] ?? __('status.completed') }}</option></select><button class="button" type="submit">{{ __('common.save') }}</button></form></td></tr>@empty<tr><td colspan="5"><x-empty-state /></td></tr>@endforelse</tbody></table></div></section>
        @endif

        @if(in_array($page, ['follow-ups','no-shows'], true))
            @php($rows = $page === 'follow-ups' ? $followUps : $noShows)
            <section class="table-card"><div class="table-scroll"><table><thead><tr><th>{{ __('common.number') }}</th><th>{{ __('patients.patient') }}</th><th>{{ __('common.date') }}</th><th>{{ __('common.branch') }}</th><th>{{ __('common.status') }}</th></tr></thead><tbody>@forelse($rows as $appointment)<tr><td>{{ $appointment->appointment_number }}</td><td>{{ $appointment->patient_name }}<br><span class="table-meta">{{ $appointment->phone ?? $appointment->whatsapp_number }}</span></td><td>{{ $appointment->appointment_at }}</td><td>{{ $appointment->branch_name }}</td><td><x-status-badge :status="$appointment->status" /></td></tr>@empty<tr><td colspan="5"><x-empty-state /></td></tr>@endforelse</tbody></table></div></section>
        @endif

        @if($page === 'reports')
            <div class="module-grid">@foreach($reports as $key => $label)<x-module-card icon="reports" :title="__('appointments.report.'.$key)" :description="__('reports.description')" :action="__('common.open')" :href="url('/api/v1/appointments/reports/'.str_replace('_','-',$key))" />@endforeach</div>
        @endif

        @if($page === 'reschedule-cancel')<x-empty-state :title="__('appointments.page.reschedule-cancel')" :message="__('appointments.use_details_hint')" />@endif
    @endif
@endsection
