@extends('layouts.erp', ['activeNav' => 'patients'])

@section('title', __('nav.patients'))

@php
    $profile = $profile ?? [];
    $profilePatient = $profile['patient'] ?? $selectedPatient ?? null;
    $patientCards = [
        ['icon' => 'patients', 'key' => 'list', 'page' => 'patients', 'count' => $metrics['total_patients'] ?? 0],
        ['icon' => 'plus', 'key' => 'new', 'page' => 'patient-create', 'count' => null],
        ['icon' => 'appointments', 'key' => 'exams', 'page' => 'eye-exam', 'count' => $metrics['exams_today'] ?? 0],
        ['icon' => 'reports', 'key' => 'prescriptions', 'page' => 'prescription', 'count' => $metrics['prescriptions_month'] ?? 0],
        ['icon' => 'reports', 'key' => 'documents', 'page' => 'documents', 'count' => $metrics['documents'] ?? 0],
        ['icon' => 'whatsapp', 'key' => 'followups', 'page' => 'follow-ups', 'count' => $metrics['followups_due'] ?? 0],
    ];
    $eyeFields = ['sph' => 'SPH', 'cyl' => 'CYL', 'axis' => __('patients.axis'), 'add' => 'ADD', 'pd' => 'PD', 'va' => 'VA'];
@endphp

@section('content')
    @if (! $databaseReady)
        <x-empty-state :title="__('setup.database_not_ready')" :message="__('setup.run_migrations')" />
    @else
        <section class="page-header"><div><p class="eyebrow">{{ __('nav.patients') }}</p><h1>{{ __('patients.page.'.$page) }}</h1><p>{{ __('patients.subtitle') }}</p></div><a class="button" href="{{ route('patients.app', ['page' => 'patient-create', 'lang' => app()->getLocale()]) }}"><x-icon name="plus" />{{ __('patients.new_patient') }}</a></section>

        @if ($page === 'dashboard')
            <section class="metric-grid"><x-metric-card :label="__('patients.total')" :value="$metrics['total_patients']" :hint="__('patients.active_count', ['count' => $metrics['active_patients']])" /><x-metric-card :label="__('patients.new_month')" :value="$metrics['new_this_month']" /><x-metric-card :label="__('patients.exams_today')" :value="$metrics['exams_today']" /><x-metric-card :label="__('patients.followups_due')" :value="$metrics['followups_due']" /></section>
            <section class="section"><div class="section-header"><div><h2>{{ __('patients.workspace') }}</h2><p>{{ __('patients.workspace_hint') }}</p></div></div><div class="module-grid">@foreach($patientCards as $card)<x-module-card :icon="$card['icon']" :title="__('patients.card.'.$card['key'].'.title')" :description="__('patients.card.'.$card['key'].'.description')" :action="__('common.open')" :href="route('patients.app', ['page' => $card['page'], 'lang' => app()->getLocale()])" :count="$card['count']" />@endforeach</div></section>
        @endif

        @if ($page === 'patients')
            <form class="filterbar" method="GET"><input type="hidden" name="lang" value="{{ app()->getLocale() }}"><input name="q" value="{{ $query }}" type="search" placeholder="{{ __('patients.search_placeholder') }}"><select name="status"><option value="">{{ __('patients.all_statuses') }}</option><option value="active">{{ __('status.active') }}</option><option value="inactive">{{ __('status.inactive') }}</option></select><button class="button button-secondary" type="submit">{{ __('common.search') }}</button></form>
            <section class="table-card"><div class="table-scroll"><table><thead><tr><th>{{ __('patients.patient') }}</th><th>{{ __('common.phone') }}</th><th>{{ __('patients.whatsapp') }}</th><th>{{ __('patients.last_visit') }}</th><th>{{ __('common.status') }}</th></tr></thead><tbody>@forelse($patients as $patient)<tr><td><a href="{{ route('patients.app', ['page' => 'profile', 'patient_id' => $patient->id, 'lang' => app()->getLocale()]) }}"><strong>{{ $patient->full_name }}</strong></a><br><span class="table-meta">{{ $patient->patient_code }}</span></td><td>{{ $patient->phone ?: __('common.not_set') }}</td><td>{{ $patient->whatsapp_number ?: __('common.not_set') }}</td><td>{{ optional($patient->updated_at)->format('Y-m-d') ?? substr((string)$patient->updated_at, 0, 10) }}</td><td><x-status-badge :status="$patient->is_active ? 'active' : 'inactive'" /></td></tr>@empty<tr><td colspan="5"><x-empty-state /></td></tr>@endforelse</tbody></table></div></section>
        @endif

        @if ($page === 'patient-create')
            <form method="POST" action="{{ route('patients.store') }}" data-wizard data-draft-key="patient-create-draft">@csrf<input type="hidden" name="is_active" value="1">
                <section class="wizard"><aside class="wizard-steps">@foreach(['identity','contact','details','review'] as $index => $step)<button class="wizard-step-button {{ $index === 0 ? 'active' : '' }}" type="button" data-wizard-step="{{ $step }}"><span class="wizard-step-number">{{ $index + 1 }}</span><span>{{ __('patients.step.'.$step) }}</span></button>@endforeach</aside><div>
                    <div class="wizard-panel active" data-wizard-panel="identity"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('patients.step.identity') }}</h2><div class="form-grid"><div class="field"><label class="required">{{ __('patients.full_name') }}</label><input name="full_name" required placeholder="{{ __('patients.full_name_placeholder') }}"></div><div class="field"><label>{{ __('patients.patient_code') }}</label><input name="patient_code" placeholder="{{ __('patients.auto_number') }}"></div><div class="field"><label>{{ __('patients.gender') }}</label><select name="gender">@foreach($genders as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('patients.birth_date') }}</label><input name="date_of_birth" type="date"></div></div><div class="wizard-actions"><a class="button button-ghost" href="{{ route('patients.app', ['page' => 'dashboard']) }}">{{ __('common.cancel') }}</a><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="contact"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('patients.step.contact') }}</h2><div class="form-grid"><div class="field"><label>{{ __('common.phone') }}</label><input name="phone" type="tel" placeholder="+966 5x xxx xxxx"></div><div class="field"><label>{{ __('patients.whatsapp') }}</label><input name="whatsapp_number" type="tel" placeholder="+966 5x xxx xxxx"></div><div class="field"><label>{{ __('common.email') }}</label><input name="email" type="email" placeholder="name@example.com"></div><div class="field"><label>{{ __('common.address') }}</label><input name="address"></div></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="details"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('patients.step.details') }}</h2><div class="form-grid"><div class="field"><label>{{ __('patients.emergency_name') }}</label><input name="emergency_contact_name"></div><div class="field"><label>{{ __('patients.emergency_phone') }}</label><input name="emergency_contact_phone" type="tel"></div><details class="more-details"><summary>{{ __('common.more_details') }}</summary><div class="field" style="margin-top:12px"><label>{{ __('common.notes') }}</label><textarea name="notes"></textarea></div></details></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="review"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('patients.review') }}</h2><p>{{ __('patients.review_hint') }}</p><div class="notice notice-success">{{ __('common.draft_saved') }}</div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="submit">{{ __('patients.save_patient') }}</button></div></div>
                </div></section>
            </form>
        @endif

        @if ($page === 'profile')
            @if($profilePatient)
                <section class="panel"><div class="section-header"><div><h2>{{ $profilePatient->full_name }}</h2><p>{{ $profilePatient->patient_code }} / {{ $profilePatient->phone ?? $profilePatient->whatsapp_number }}</p></div><x-status-badge :status="$profilePatient->is_active ? 'active' : 'inactive'" /></div><div class="metric-grid"><x-metric-card :label="__('patients.appointments')" :value="($profile['appointments'] ?? collect())->count()" /><x-metric-card :label="__('patients.exams')" :value="($profile['exams'] ?? collect())->count()" /><x-metric-card :label="__('patients.prescriptions')" :value="($profile['prescriptions'] ?? collect())->count()" /><x-metric-card :label="__('patients.documents')" :value="($profile['documents'] ?? collect())->count()" /></div><div class="form-actions"><a class="button button-ghost" href="{{ route('appointments.app', ['page' => 'create', 'patient_id' => $profilePatient->id]) }}">{{ __('patients.book_appointment') }}</a><a class="button" href="{{ route('patients.app', ['page' => 'eye-exam', 'patient_id' => $profilePatient->id]) }}">{{ __('patients.new_exam') }}</a><a class="button button-secondary" href="{{ route('documents.patient-files.show', ['patient' => $profilePatient->id, 'lang' => app()->getLocale()]) }}">{{ __('common.print') }}</a><a class="button button-ghost" href="{{ route('documents.patient-files.show', ['patient' => $profilePatient->id, 'lang' => app()->getLocale(), 'format' => 'pdf']) }}">PDF</a></div></section>
                <section class="section table-card"><div class="table-scroll"><table><thead><tr><th>{{ __('common.date') }}</th><th>{{ __('common.type') }}</th><th>{{ __('common.description') }}</th><th>{{ __('common.branch') }}</th></tr></thead><tbody>@forelse(($profile['timeline'] ?? collect()) as $event)<tr><td>{{ $event->event_at }}</td><td>{{ $event->event_type }}</td><td>{{ $event->event_title }}<br><span class="table-meta">{{ $event->description }}</span></td><td>{{ $event->branch_name ?: __('common.not_set') }}</td></tr>@empty<tr><td colspan="4"><x-empty-state /></td></tr>@endforelse</tbody></table></div></section>
            @else<x-empty-state />@endif
        @endif

        @if ($page === 'eye-exam')
            <form method="POST" action="{{ route('patients.exams.store') }}" data-wizard data-draft-key="eye-exam-draft">@csrf
                <section class="wizard"><aside class="wizard-steps">@foreach(['visit','right_eye','left_eye','clinical','review'] as $index => $step)<button class="wizard-step-button {{ $index === 0 ? 'active' : '' }}" type="button" data-wizard-step="{{ $step }}"><span class="wizard-step-number">{{ $index + 1 }}</span><span>{{ __('patients.exam_step.'.$step) }}</span></button>@endforeach</aside><div>
                    <div class="wizard-panel active" data-wizard-panel="visit"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('patients.exam_step.visit') }}</h2><div class="form-grid"><div class="field"><label class="required">{{ __('patients.patient') }}</label><select name="patient_id" required>@foreach($patients as $patient)<option value="{{ $patient->id }}" @selected(request('patient_id') == $patient->id)>{{ $patient->patient_code }} - {{ $patient->full_name }}</option>@endforeach</select></div><div class="field"><label>{{ __('common.branch') }}</label><select name="branch_id">@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($branchId === (int)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="field"><label>{{ __('patients.optometrist') }}</label><select name="optometrist_id"><option value="">{{ __('common.not_set') }}</option>@foreach($optometrists as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div><div class="field"><label>{{ __('common.date') }}</label><input name="exam_date" type="date" value="{{ now()->toDateString() }}"></div><input type="hidden" name="status" value="completed"></div><div class="wizard-actions"><a class="button button-ghost" href="{{ route('patients.app', ['page' => 'dashboard']) }}">{{ __('common.cancel') }}</a><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    @foreach(['right_eye' => 'right', 'left_eye' => 'left'] as $panel => $side)
                        <div class="wizard-panel" data-wizard-panel="{{ $panel }}"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('patients.exam_step.'.$panel) }}</h2><div class="form-grid">@foreach($eyeFields as $field => $label)<div class="field"><label>{{ $label }}</label><input name="{{ $side }}_{{ $field }}" @if($field !== 'va') type="number" step="0.01" @endif></div>@endforeach</div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    @endforeach
                    <div class="wizard-panel" data-wizard-panel="clinical"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('patients.exam_step.clinical') }}</h2><div class="form-grid"><div class="field field-wide"><label>{{ __('patients.diagnosis') }}</label><textarea name="diagnosis"></textarea></div><div class="field field-wide"><label>{{ __('patients.recommendation') }}</label><textarea name="recommendation"></textarea></div><details class="more-details"><summary>{{ __('common.more_details') }}</summary><div class="form-grid" style="margin-top:12px"><div class="field"><label>{{ __('patients.next_visit') }}</label><input name="next_visit_date" type="date"></div><div class="field"><label>{{ __('common.notes') }}</label><textarea name="optometrist_notes"></textarea></div></div></details></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="review"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('patients.exam_step.review') }}</h2><p>{{ __('patients.exam_review_hint') }}</p><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="submit">{{ __('patients.save_exam') }}</button></div></div>
                </div></section>
            </form>
        @endif

        @if ($page === 'prescription')
            <section class="panel"><div class="section-header"><div><h2>{{ __('patients.new_prescription') }}</h2><p>{{ __('patients.prescription_hint') }}</p></div></div><form class="form-grid" method="POST" action="{{ route('patients.prescriptions.store') }}">@csrf<div class="field"><label class="required">{{ __('patients.patient') }}</label><select name="patient_id" required>@foreach($patients as $patient)<option value="{{ $patient->id }}" @selected(request('patient_id') == $patient->id)>{{ $patient->patient_code }} - {{ $patient->full_name }}</option>@endforeach</select></div><div class="field"><label>{{ __('patients.source_exam') }}</label><select name="patient_eye_exam_id"><option value="">{{ __('patients.manual_prescription') }}</option>@foreach($recentExams as $exam)<option value="{{ $exam->id }}">{{ $exam->exam_number }} - {{ $exam->full_name }}</option>@endforeach</select></div><div class="field"><label>{{ __('common.status') }}</label><select name="status">@foreach($prescriptionStatuses as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>@foreach(['right' => __('patients.right_eye'), 'left' => __('patients.left_eye')] as $side => $sideLabel)<div class="field field-wide"><label>{{ $sideLabel }}</label><div class="form-grid">@foreach($eyeFields as $field => $label)<div class="field"><label>{{ $label }}</label><input name="{{ $side }}_{{ $field }}" @if($field !== 'va') type="number" step="0.01" @endif></div>@endforeach</div></div>@endforeach<details class="more-details"><summary>{{ __('common.more_details') }}</summary><div class="form-grid" style="margin-top:12px"><div class="field"><label>{{ __('patients.diagnosis') }}</label><textarea name="diagnosis"></textarea></div><div class="field"><label>{{ __('patients.recommendation') }}</label><textarea name="recommendation"></textarea></div></div></details><div class="form-actions"><button class="button" type="submit">{{ __('patients.save_prescription') }}</button></div></form></section>
        @endif

        @if ($page === 'documents')
            <section class="panel"><div class="section-header"><div><h2>{{ __('patients.upload_document') }}</h2><p>{{ __('patients.document_hint') }}</p></div></div><form class="form-grid" method="POST" action="{{ route('patients.documents.store') }}" enctype="multipart/form-data">@csrf<div class="field"><label class="required">{{ __('patients.patient') }}</label><select name="patient_id" required>@foreach($patients as $patient)<option value="{{ $patient->id }}">{{ $patient->patient_code }} - {{ $patient->full_name }}</option>@endforeach</select></div><div class="field"><label class="required">{{ __('common.type') }}</label><select name="document_type" required>@foreach($documentTypes as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label class="required">{{ __('patients.document_title') }}</label><input name="title" required></div><div class="field"><label>{{ __('patients.file') }}</label><input name="document" type="file" accept=".pdf,.jpg,.jpeg,.png"></div><details class="more-details"><summary>{{ __('common.more_details') }}</summary><div class="field" style="margin-top:12px"><label>{{ __('common.notes') }}</label><textarea name="notes"></textarea></div></details><div class="form-actions"><button class="button" type="submit">{{ __('patients.save_document') }}</button></div></form></section>
        @endif

        @if ($page === 'follow-ups')
            <section class="table-card"><div class="table-scroll"><table><thead><tr><th>{{ __('patients.patient') }}</th><th>{{ __('patients.next_visit') }}</th><th>{{ __('common.phone') }}</th><th>{{ __('patients.optometrist') }}</th><th>{{ __('common.status') }}</th></tr></thead><tbody>@forelse($followUps as $row)<tr><td><a href="{{ route('patients.app', ['page' => 'profile', 'patient_id' => $row->patient_id]) }}"><strong>{{ $row->full_name }}</strong></a><br><span class="table-meta">{{ $row->patient_code }}</span></td><td>{{ $row->next_visit_date }}</td><td>{{ $row->phone ?? $row->whatsapp_number }}</td><td>{{ $row->optometrist_name ?: __('common.not_set') }}</td><td><x-status-badge status="pending" /></td></tr>@empty<tr><td colspan="5"><x-empty-state /></td></tr>@endforelse</tbody></table></div></section>
        @endif

        @if ($page === 'prescription-print')
            @if($printPrescription)<section class="panel"><div class="section-header"><div><h2>{{ __('patients.optical_prescription') }}</h2><p>{{ $printPrescription->prescription_number }}</p></div><div class="form-actions"><a class="button" href="{{ route('documents.prescriptions.show', ['prescription' => $printPrescription->id, 'lang' => app()->getLocale()]) }}">{{ __('common.print') }}</a><a class="button button-secondary" href="{{ route('documents.prescriptions.show', ['prescription' => $printPrescription->id, 'lang' => app()->getLocale(), 'format' => 'pdf']) }}">PDF</a></div></div></section>@else<x-empty-state />@endif
        @endif

        @if(in_array($page, ['timeline','reports'], true))
            <x-empty-state :title="__('patients.page.'.$page)" :message="__('patients.use_profile_hint')" />
        @endif
    @endif
@endsection
