@extends('layouts.erp', ['activeNav' => 'optical-orders'])

@section('title', __('nav.optical_orders'))

@php
    $currency = config('erp.module.currency', 'SAR');
    $money = fn ($value) => $currency.' '.number_format((float) $value, 2);
    $selected = $selectedOrder ?? [];
    $currentOrder = $selected['order'] ?? null;
    $cards = [
        ['icon' => 'plus', 'key' => 'new', 'page' => 'create', 'count' => null],
        ['icon' => 'orders', 'key' => 'orders', 'page' => 'dashboard', 'count' => $metrics['open_orders'] ?? 0],
        ['icon' => 'configuration', 'key' => 'lab', 'page' => 'lab-board', 'count' => $metrics['in_lab'] ?? 0],
        ['icon' => 'sales', 'key' => 'pickup', 'page' => 'ready-pickup', 'count' => $metrics['ready_for_pickup'] ?? 0],
        ['icon' => 'reports', 'key' => 'delayed', 'page' => 'lab-board', 'count' => $metrics['delayed'] ?? 0],
        ['icon' => 'reports', 'key' => 'reports', 'page' => 'reports', 'count' => null],
    ];
@endphp

@section('content')
    @if (! $databaseReady)
        <x-empty-state :title="__('setup.database_not_ready')" :message="__('setup.run_migrations')" />
    @else
        <section class="page-header"><div><p class="eyebrow">{{ __('nav.optical_orders') }}</p><h1>{{ __('orders.page.'.$page) }}</h1><p>{{ __('orders.subtitle') }}</p></div><a class="button" href="{{ route('optical-orders.app', ['page' => 'create', 'lang' => app()->getLocale()]) }}"><x-icon name="plus" />{{ __('orders.new_order') }}</a></section>

        @if($page === 'dashboard')
            <section class="metric-grid"><x-metric-card :label="__('orders.open_orders')" :value="$metrics['open_orders']" /><x-metric-card :label="__('orders.in_lab')" :value="$metrics['in_lab']" /><x-metric-card :label="__('orders.ready_pickup')" :value="$metrics['ready_for_pickup']" /><x-metric-card :label="__('orders.outstanding')" :value="$money($metrics['outstanding'])" /></section>
            <section class="section"><div class="section-header"><div><h2>{{ __('orders.workspace') }}</h2><p>{{ __('orders.workspace_hint') }}</p></div></div><div class="module-grid">@foreach($cards as $card)<x-module-card :icon="$card['icon']" :title="__('orders.card.'.$card['key'].'.title')" :description="__('orders.card.'.$card['key'].'.description')" :action="__('common.open')" :href="route('optical-orders.app', ['page' => $card['page'], 'lang' => app()->getLocale()])" :count="$card['count']" />@endforeach</div></section>
            <section class="section table-card"><div class="section-header panel"><div><h2>{{ __('orders.recent_orders') }}</h2></div></div>@include('optical-orders.partials.simple-table', ['tableOrders' => $orders])</section>
        @endif

        @if($page === 'create')
            <form method="POST" action="{{ route('optical-orders.store') }}" data-wizard data-draft-key="optical-order-draft">@csrf<input type="hidden" name="status" value="confirmed"><input type="hidden" name="lens_quantity" value="1">
                <section class="wizard"><aside class="wizard-steps">@foreach(['patient','frame','lens','payment','review'] as $index => $step)<button class="wizard-step-button {{ $index === 0 ? 'active' : '' }}" type="button" data-wizard-step="{{ $step }}"><span class="wizard-step-number">{{ $index + 1 }}</span><span>{{ __('orders.step.'.$step) }}</span></button>@endforeach</aside><div>
                    <div class="wizard-panel active" data-wizard-panel="patient"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('orders.choose_patient_rx') }}</h2><div class="form-grid"><div class="field"><label class="required">{{ __('patients.patient') }}</label><select name="patient_id" required>@foreach($patients as $patient)<option value="{{ $patient->id }}" @selected(request('patient_id') == $patient->id)>{{ $patient->patient_code }} - {{ $patient->full_name }}</option>@endforeach</select></div><div class="field"><label>{{ __('orders.prescription') }}</label><select name="patient_prescription_id"><option value="">{{ __('orders.latest_prescription') }}</option>@foreach($prescriptions as $rx)<option value="{{ $rx->id }}">{{ $rx->prescription_number }} - {{ $rx->full_name }}</option>@endforeach</select></div><div class="field"><label class="required">{{ __('common.branch') }}</label><select name="branch_id" required>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($branchId === (int)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="field"><label>{{ __('orders.salesperson') }}</label><select name="salesperson_id"><option value="">{{ __('common.not_set') }}</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div></div><div class="wizard-actions"><a class="button button-ghost" href="{{ route('optical-orders.app', ['page' => 'dashboard']) }}">{{ __('common.cancel') }}</a><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="frame"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('orders.choose_frame') }}</h2><div class="form-grid"><div class="field field-wide"><label class="required">{{ __('orders.frame') }}</label><select name="frame_product_id" required><option value="">{{ __('orders.select_frame') }}</option>@foreach($frames as $frame)<option value="{{ $frame->id }}">{{ $frame->sku }} - {{ $frame->name }} - {{ $money($frame->retail_price) }}</option>@endforeach</select></div><div class="field"><label>{{ __('orders.frame_price') }}</label><input name="frame_unit_price" type="number" min="0" step="0.01" placeholder="{{ __('orders.use_catalog_price') }}"></div><div class="field"><label>{{ __('orders.priority') }}</label><select name="priority">@foreach($priorities as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="lens"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('orders.choose_lens') }}</h2><div class="form-grid"><div class="field field-wide"><label class="required">{{ __('orders.lens_product') }}</label><select name="lens_product_id" required><option value="">{{ __('orders.select_lens') }}</option>@foreach($lenses as $lens)<option value="{{ $lens->id }}">{{ $lens->sku }} - {{ $lens->name }} - {{ $money($lens->retail_price) }}</option>@endforeach</select></div><div class="field"><label>{{ __('configuration.lens_types') }}</label><select name="lens_type">@foreach($lensTypes as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('configuration.lens_materials') }}</label><select name="lens_material">@foreach($lensMaterials as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('orders.lens_index') }}</label><select name="lens_index">@foreach($lensIndexes as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('configuration.lens_coatings') }}</label><select name="coating">@foreach($coatings as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('configuration.lens_tints') }}</label><select name="tint">@foreach($tints as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('orders.lab') }}</label><select name="lab_supplier_id"><option value="">{{ __('common.not_set') }}</option>@foreach($labs as $lab)<option value="{{ $lab->id }}">{{ $lab->name }}</option>@endforeach</select></div></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="payment"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('orders.deposit_delivery') }}</h2><div class="form-grid"><div class="field"><label>{{ __('orders.deposit') }}</label><input name="deposit_amount" type="number" min="0" step="0.01" value="0"></div><div class="field"><label>{{ __('orders.payment_method') }}</label><select name="deposit_method">@foreach($paymentMethods as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('orders.expected_delivery') }}</label><input name="expected_delivery_date" type="date" value="{{ now()->addDays(3)->toDateString() }}"></div><details class="more-details"><summary>{{ __('common.more_details') }}</summary><div class="form-grid" style="margin-top:12px"><div class="field"><label>{{ __('orders.fitting_notes') }}</label><textarea name="fitting_notes"></textarea></div><div class="field"><label>{{ __('orders.special_instructions') }}</label><textarea name="special_instructions"></textarea></div></div></details></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="review"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('orders.review_order') }}</h2><p>{{ __('orders.review_hint') }}</p><div class="notice notice-success">{{ __('common.draft_saved') }}</div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="submit">{{ __('orders.create_order') }}</button></div></div>
                </div></section>
            </form>
        @endif

        @if(in_array($page, ['lab-board','ready-pickup'], true))
            @php($tableOrders = $page === 'ready-pickup' ? $readyOrders : $orders)
            <form class="filterbar" method="GET"><input type="hidden" name="lang" value="{{ app()->getLocale() }}"><input name="q" value="{{ $query }}" type="search" placeholder="{{ __('orders.search_placeholder') }}"><select name="status"><option value="">{{ __('orders.all_statuses') }}</option>@foreach($statuses as $key => $label)<option value="{{ $key }}" @selected($statusFilter === $key)>{{ $label }}</option>@endforeach</select><button class="button button-secondary" type="submit">{{ __('common.search') }}</button></form>
            <section class="table-card">@include('optical-orders.partials.simple-table', ['tableOrders' => $tableOrders])</section>
        @endif

        @if($page === 'details')
            @if($currentOrder)
                <section class="panel"><div class="section-header"><div><h2>{{ $currentOrder->order_number }}</h2><p>{{ $currentOrder->patient_name }} / {{ $currentOrder->phone ?? $currentOrder->whatsapp_number }}</p></div><div class="form-actions"><x-status-badge :status="$currentOrder->status" /><a class="button button-ghost" href="{{ route('documents.optical-orders.show', ['order' => $currentOrder->id, 'lang' => app()->getLocale()]) }}">{{ __('common.print') }}</a><a class="button button-ghost" href="{{ route('documents.optical-orders.glasses-card', ['order' => $currentOrder->id, 'lang' => app()->getLocale()]) }}">{{ __('Card') }}</a><a class="button button-secondary" href="{{ route('documents.optical-orders.show', ['order' => $currentOrder->id, 'lang' => app()->getLocale(), 'format' => 'pdf']) }}">PDF</a></div></div><div class="metric-grid"><x-metric-card :label="__('common.total')" :value="$money($currentOrder->grand_total)" /><x-metric-card :label="__('orders.paid')" :value="$money($currentOrder->paid_amount)" /><x-metric-card :label="__('orders.outstanding')" :value="$money($currentOrder->outstanding_amount)" /><x-metric-card :label="__('orders.expected_delivery')" :value="$currentOrder->expected_delivery_date" /></div><div class="cards-grid"><form class="panel form-grid" method="POST" action="{{ route('optical-orders.status') }}">@csrf<input type="hidden" name="order_id" value="{{ $currentOrder->id }}"><div class="field"><label>{{ __('common.status') }}</label><select name="status">@foreach($statuses as $key => $label)<option value="{{ $key }}" @selected($currentOrder->status === $key)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>{{ __('common.notes') }}</label><input name="notes"></div><div class="form-actions"><button class="button" type="submit">{{ __('orders.update_status') }}</button></div></form><form class="panel form-grid" method="POST" action="{{ route('optical-orders.payments.store') }}">@csrf<input type="hidden" name="order_id" value="{{ $currentOrder->id }}"><div class="field"><label>{{ __('orders.payment_amount') }}</label><input name="amount" type="number" min="0.01" step="0.01" required value="{{ $currentOrder->outstanding_amount }}"></div><div class="field"><label>{{ __('orders.payment_method') }}</label><select name="payment_method">@foreach($paymentMethods as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="form-actions"><button class="button" type="submit">{{ __('orders.collect_payment') }}</button></div></form></div></section>
            @else<x-empty-state />@endif
        @endif

        @if($page === 'reports')<div class="module-grid">@foreach($reports as $key => $label)<x-module-card icon="reports" :title="__('orders.report.'.$key)" :description="__('reports.description')" :action="__('common.open')" :href="url('/api/v1/optical-orders/reports/'.str_replace('_','-',$key))" />@endforeach</div>@endif

        @if(in_array($page, ['remake-cancel','documents','timeline','print'], true))
            <x-empty-state :title="__('orders.page.'.$page)" :message="__('orders.use_main_workflow')" />
        @endif
    @endif
@endsection
