@extends('layouts.erp', ['activeNav' => 'sales-pos'])

@section('title', __('nav.sales_pos'))

@php
    $currency = config('erp.module.currency', 'SAR');
    $money = fn ($value) => $currency.' '.number_format((float) $value, 2);
    $cards = [
        ['icon' => 'sales', 'key' => 'pos', 'page' => 'pos', 'count' => null],
        ['icon' => 'reports', 'key' => 'invoices', 'page' => 'invoices', 'count' => $metrics['daily_sales'] ?? 0],
        ['icon' => 'accounting', 'key' => 'payments', 'page' => 'payments', 'count' => $payments->count() ?? 0],
        ['icon' => 'orders', 'key' => 'orders', 'page' => 'sales-orders', 'count' => $metrics['pending_orders'] ?? 0],
        ['icon' => 'configuration', 'key' => 'returns', 'page' => 'returns', 'count' => null],
        ['icon' => 'accounting', 'key' => 'closing', 'page' => 'cashier-closing', 'count' => null],
    ];
@endphp

@section('content')
    @if (! $databaseReady)
        <x-empty-state :title="__('setup.database_not_ready')" :message="__('setup.run_migrations')" />
    @else
        <section class="page-header"><div><p class="eyebrow">{{ __('nav.sales_pos') }}</p><h1>{{ __('sales.page.'.$page) }}</h1><p>{{ __('sales.subtitle') }}</p></div><a class="button" href="{{ route('sales.app', ['page' => 'pos', 'lang' => app()->getLocale()]) }}"><x-icon name="sales" />{{ __('sales.new_sale') }}</a></section>

        @if($page === 'dashboard')
            <section class="metric-grid"><x-metric-card :label="__('sales.revenue_today')" :value="$money($metrics['daily_revenue'])" /><x-metric-card :label="__('sales.paid_today')" :value="$money($metrics['daily_paid'])" /><x-metric-card :label="__('sales.pending_balance')" :value="$money($metrics['pending_balance'])" /><x-metric-card :label="__('sales.gross_profit')" :value="$money($metrics['gross_profit'])" /></section>
            <section class="section"><div class="section-header"><div><h2>{{ __('sales.workspace') }}</h2><p>{{ __('sales.workspace_hint') }}</p></div></div><div class="module-grid">@foreach($cards as $card)<x-module-card :icon="$card['icon']" :title="__('sales.card.'.$card['key'].'.title')" :description="__('sales.card.'.$card['key'].'.description')" :action="__('common.open')" :href="route('sales.app', ['page' => $card['page'], 'lang' => app()->getLocale()])" :count="$card['count']" />@endforeach</div></section>
        @endif

        @if($page === 'pos')
            <form method="POST" action="{{ route('sales.checkout') }}" data-wizard data-draft-key="pos-checkout-draft" data-pos>@csrf<input type="hidden" name="sale_mode" value="ready_product"><input type="hidden" name="pickup_status" value="not_required">
                <section class="wizard"><aside class="wizard-steps">@foreach(['products','cart','payment','review'] as $index => $step)<button class="wizard-step-button {{ $index === 0 ? 'active' : '' }}" type="button" data-wizard-step="{{ $step }}"><span class="wizard-step-number">{{ $index + 1 }}</span><span>{{ __('sales.step.'.$step) }}</span></button>@endforeach</aside><div>
                    <div class="wizard-panel active" data-wizard-panel="products"><div class="wizard-progress"><span data-wizard-progress></span></div><div class="section-header"><div><h2>{{ __('sales.find_products') }}</h2><p>{{ __('sales.find_products_hint') }}</p></div></div><div class="product-grid">@forelse($products as $product)<button class="product-tile" type="button" data-product="{{ $product->id }}" data-name="{{ $product->name }}" data-price="{{ $product->retail_price }}"><strong>{{ $product->name }}</strong><span class="table-meta">{{ $product->sku }} / {{ $product->barcode }}</span><span>{{ $money($product->retail_price) }}</span><x-status-badge :status="$product->available_stock > 0 ? 'active' : 'low_stock'" /></button>@empty<x-empty-state />@endforelse</div><div class="wizard-actions"><a class="button button-ghost" href="{{ route('sales.app', ['page' => 'dashboard']) }}">{{ __('common.cancel') }}</a><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="cart"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('sales.cart_customer') }}</h2><div class="pos-layout"><div><div class="cart-list" data-cart-lines></div><x-empty-state data-cart-empty :title="__('sales.empty_cart')" :message="__('sales.empty_cart_hint')" /></div><div class="panel"><div class="field"><label>{{ __('sales.customer') }}</label><select name="customer_id"><option value="">{{ __('sales.walk_in') }}</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }} - {{ $customer->phone }}</option>@endforeach</select></div><div class="field" style="margin-top:12px"><label class="required">{{ __('common.branch') }}</label><select name="branch_id" required>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($branchId === (int)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="field" style="margin-top:12px"><label>{{ __('sales.cashier') }}</label><select name="cashier_id"><option value="">{{ __('common.not_set') }}</option>@foreach($cashiers as $cashier)<option value="{{ $cashier->id }}">{{ $cashier->name }}</option>@endforeach</select></div><div class="cart-total"><span>{{ __('common.total') }}</span><strong>{{ $currency }} <span data-cart-total>0.00</span></strong></div></div></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="payment"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('sales.payment') }}</h2><div class="form-grid"><div class="field"><label class="required">{{ __('orders.payment_method') }}</label><select name="payments[0][payment_method]" required>@foreach($paymentMethods as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label class="required">{{ __('orders.payment_amount') }}</label><input name="payments[0][amount]" data-payment-amount type="number" min="0" step="0.01" required></div><details class="more-details"><summary>{{ __('common.more_details') }}</summary><div class="form-grid" style="margin-top:12px"><div class="field"><label>{{ __('sales.payment_reference') }}</label><input name="payments[0][reference]"></div><div class="field"><label>{{ __('common.notes') }}</label><textarea name="notes"></textarea></div></div></details></div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="button" data-wizard-next>{{ __('common.next') }}</button></div></div>
                    <div class="wizard-panel" data-wizard-panel="review"><div class="wizard-progress"><span data-wizard-progress></span></div><h2>{{ __('sales.review_sale') }}</h2><p>{{ __('sales.review_hint') }}</p><div class="notice notice-success">{{ __('sales.invoice_after_post') }}</div><div class="wizard-actions"><button class="button button-ghost" type="button" data-wizard-back>{{ __('common.back') }}</button><button class="button" type="submit">{{ __('sales.pay_create_invoice') }}</button></div></div>
                </div></section>
            </form>
        @endif

        @if($page === 'invoices')
            <section class="table-card"><div class="table-scroll"><table><thead><tr><th>{{ __('common.number') }}</th><th>{{ __('sales.customer') }}</th><th>{{ __('common.date') }}</th><th>{{ __('common.total') }}</th><th>{{ __('orders.paid') }}</th><th>{{ __('orders.outstanding') }}</th><th>{{ __('common.status') }}</th><th>{{ __('common.actions') }}</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td><strong>{{ $invoice->invoice_number }}</strong></td><td>{{ $invoice->customer_name ?: __('sales.walk_in') }}</td><td>{{ $invoice->invoice_date }}</td><td>{{ $money($invoice->grand_total) }}</td><td>{{ $money($invoice->paid_total) }}</td><td>{{ $money($invoice->balance_due) }}</td><td><x-status-badge :status="$invoice->status" /></td><td><a class="button button-ghost" href="{{ route('documents.sales-invoices.show', ['invoice' => $invoice->id, 'lang' => app()->getLocale()]) }}">{{ __('common.print') }}</a><a class="button button-ghost" href="{{ route('documents.sales-invoices.show', ['invoice' => $invoice->id, 'lang' => app()->getLocale(), 'format' => 'pdf']) }}">PDF</a></td></tr>@empty<tr><td colspan="8"><x-empty-state /></td></tr>@endforelse</tbody></table></div></section>
        @endif

        @if($page === 'payments')
            <section class="table-card"><div class="table-scroll"><table><thead><tr><th>{{ __('common.number') }}</th><th>{{ __('sales.customer') }}</th><th>{{ __('orders.payment_method') }}</th><th>{{ __('orders.payment_amount') }}</th><th>{{ __('common.date') }}</th><th>{{ __('common.status') }}</th><th>{{ __('common.actions') }}</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->payment_number }}</td><td>{{ $payment->customer_name ?: __('sales.walk_in') }}</td><td>{{ $paymentMethods[$payment->payment_method] ?? $payment->payment_method }}</td><td>{{ $money($payment->amount) }}</td><td>{{ $payment->paid_at }}</td><td><x-status-badge :status="$payment->status" /></td><td><a class="button button-ghost" href="{{ route('documents.payments.voucher', ['payment' => $payment->id, 'lang' => app()->getLocale()]) }}">{{ __('common.print') }}</a><a class="button button-ghost" href="{{ route('documents.payments.receipt', ['payment' => $payment->id, 'lang' => app()->getLocale(), 'format' => 'pdf']) }}">PDF</a></td></tr>@empty<tr><td colspan="7"><x-empty-state /></td></tr>@endforelse</tbody></table></div></section>
        @endif

        @if($page === 'cashier-closing')
            @if($openSession)<section class="panel"><div class="section-header"><div><h2>{{ __('sales.close_day') }}</h2><p>{{ $openSession->session_number }}</p></div></div><div class="metric-grid"><x-metric-card :label="__('sales.opening_cash')" :value="$money($openSession->opening_cash)" /><x-metric-card :label="__('sales.cash_sales')" :value="$money($openSession->total_cash_sales)" /><x-metric-card :label="__('sales.refunds')" :value="$money($openSession->total_refunds)" /><x-metric-card :label="__('sales.expected_cash')" :value="$money($openSession->expected_cash)" /></div><form class="form-grid" method="POST" action="{{ route('sales.cashier.close') }}">@csrf<input type="hidden" name="cash_session_id" value="{{ $openSession->id }}"><div class="field"><label class="required">{{ __('sales.actual_cash') }}</label><input name="actual_cash" type="number" min="0" step="0.01" required value="{{ $openSession->expected_cash }}"></div><details class="more-details"><summary>{{ __('common.more_details') }}</summary><div class="field" style="margin-top:12px"><label>{{ __('common.notes') }}</label><textarea name="notes"></textarea></div></details><div class="form-actions"><button class="button" type="submit">{{ __('sales.close_cashier') }}</button></div></form></section>@else<x-empty-state :title="__('sales.no_open_session')" :message="__('sales.no_open_session_hint')" />@endif
        @endif

        @if($page === 'print')
            @if($printInvoice)<section class="panel"><div class="section-header"><div><h2>{{ __('sales.invoice') }} {{ $printInvoice->invoice_number }}</h2><p>{{ __('The branded invoice opens in a clean print workspace.') }}</p></div><div class="form-actions"><a class="button" href="{{ route('documents.sales-invoices.show', ['invoice' => $printInvoice->id, 'lang' => app()->getLocale()]) }}">{{ __('common.print') }}</a><a class="button button-secondary" href="{{ route('documents.sales-invoices.show', ['invoice' => $printInvoice->id, 'lang' => app()->getLocale(), 'format' => 'pdf']) }}">PDF</a></div></div></section>@else<x-empty-state />@endif
        @endif

        @if(in_array($page, ['quotations','sales-orders','returns'], true))
            <x-empty-state :title="__('sales.page.'.$page)" :message="__('sales.simplified_hint')" />
        @endif
    @endif
@endsection
